DROP TABLE IF EXISTS edits, snapshots, compositions;

CREATE TABLE compositions (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR NOT NULL,
  hash VARCHAR NOT NULL,
  version INTEGER NOT NULL
);

CREATE UNIQUE INDEX ON compositions(hash);

CREATE TABLE edits (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  composition_id INTEGER REFERENCES compositions(id) ON DELETE CASCADE,
  version INT NOT NULL,
  uuid VARCHAR NOT NULL,
  action VARCHAR NOT NULL,
  pitch VARCHAR NOT NULL,
  measure INTEGER NOT NULL,
  start INTEGER NOT NULL,
  duration INTEGER
);

CREATE INDEX ON edits(composition_id);

CREATE TABLE snapshots (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  edit_id INTEGER NOT NULL REFERENCES edits(id) ON DELETE CASCADE,
  score JSONB NOT NULL
);

CREATE UNIQUE INDEX ON snapshots(edit_id);
